import os

from dotenv import load_dotenv
from openai import OpenAI

from app.schemas import (
    FallbackBatchRequest,
    FallbackBatchResponse,
)


load_dotenv()


SYSTEM_PROMPT = """
You are the unknown-dish fallback component of FoodHub.

You receive a batch of restaurant dishes that could not be matched
by the local database or TheMealDB.

Your job is to provide neutral, generic culinary knowledge about
each dish using the provided structured output schema.

IMPORTANT EVIDENCE RULES:

1. Restaurant menu evidence is the source of truth.
   - original_name
   - menu_description
   - explicit_ingredients
   - source_text
   are restaurant-specific evidence.

2. inferred_ingredients are NOT restaurant-confirmed facts.
   - Only include ingredients that are reasonably likely based on
     general culinary knowledge.
   - Do not repeat ingredients already present in explicit_ingredients.
   - If uncertain, omit the ingredient rather than guessing strongly.

3. canonical_name_en
   - Return a concise English canonical dish name.
   - Keep the interpretation conservative.

4. description
   - Give a short neutral English explanation of the dish.
   - Do not claim that inferred ingredients are definitely used by
     this restaurant.

5. taste, texture, cooking_method, spice_level, and dish_family
   - Describe typical characteristics only when reasonably identifiable.
   - Use empty lists, null, or "unknown" when uncertain.

6. Never provide:
   - user recommendations
   - allergy decisions
   - dietary suitability
   - vegan / vegetarian / halal judgments
   - "safe" or "unsafe" claims

7. Preserve dish_id exactly.
   Return one result for every input dish.

Process the whole batch in one response.
"""


def fallback_dishes(
    request: FallbackBatchRequest,
) -> FallbackBatchResponse:
    """
    Generate structured culinary knowledge for all unmatched dishes
    using a single OpenAI call.
    """

    api_key = os.getenv("OPENAI_API_KEY")
    model = os.getenv("OPENAI_MODEL")

    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is missing from the environment."
        )

    if not model:
        raise RuntimeError(
            "OPENAI_MODEL is missing from the environment."
        )

    if not request.dishes:
        raise ValueError(
            "Fallback request must contain at least one dish."
        )

    client = OpenAI(api_key=api_key)

    response = client.responses.parse(
        model=model,
        input=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": (
                    "Provide fallback culinary knowledge for the "
                    "following unmatched dishes:\n\n"
                    f"{request.model_dump_json(indent=2)}"
                ),
            },
        ],
        text_format=FallbackBatchResponse,
    )

    result = response.output_parsed

    if result is None:
        raise RuntimeError(
            "The model did not return a valid structured fallback result."
        )

    # request_id is generated by our application, not by the model.
    result = result.model_copy(
        update={"request_id": request.request_id}
    )

    return result